[project]
name = "02_poetry_manual_demo"
version = "0.1.0"
description = ""
authors = [
    {name = "Gustavo Sarapura",email = "gustavo.sarapura7@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
package-mode = false
